package autocode

type ServiceGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	AutoCodeExampleService
	BusinessService
	IntermediaryService
	IntermediaryContactService
	ClientService
	ProjectInformationService
	BuildingInformationService
	FloorInformationService
	HousingMaintenanceService
	ContractService
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
