package autocode

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	AutoCodeExampleApi
	BusinessApi
	IntermediaryApi
	IntermediaryContactApi
	ClientApi
	ProjectInformationApi
	BuildingInformationApi
	FloorInformationApi
	HousingMaintenanceApi
	ContractApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
