package autocode

type RouterGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	AutoCodeExampleRouter
	BusinessRouter
	IntermediaryRouter
	IntermediaryContactRouter
	ClientRouter
	ProjectInformationRouter
	BuildingInformationRouter
	FloorInformationRouter
	HousingMaintenanceRouter
	ContractRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
